### ISSUE TITLE
Is it possible to configure the linter rules?

### ISSUE THREAD

**Issue by atuttle** [ckaznocha/SublimeLinter-contrib-CFLint#12]
I had [asked on CFLint](https://github.com/cflint/CFLint/issues/151) about disabling a rule and they said that it should be configurable. If it's possible with this plugin, how do I configure various rules, like the minimum length for variable names?

**Comment by ckaznocha** [comment]
Hey @atuttle it's already supported. See PR #10 and #11. The README could by updated, I'll do it soon or I'd be happy to accept a PR.
