### ISSUE TITLE
Updating for latest CFLint

### ISSUE THREAD

**Issue by KamasamaK** [ckaznocha/SublimeLinter-contrib-CFLint#13]
I wanted to update this plugin to be compatible with the latest CFLint as well as keeping it easy to use and flexible. [Here](https://github.com/KamasamaK/SublimeLinter-contrib-CFLint/tree/javaJarUpdate) is a link to my fork. Below is a summary of the major changes I've made. Please provide whatever suggestions/criticisms you have so that they may be addressed before I submit a pull request.

- Modified to use standalone JAR file instead of old batch/script file.

- Removed version attributes due to the implementation of version checking in SublimeLinter -- it would check the Java version instead. If anyone knows of a way around this, please let me know or re-implement the version checking yourself.

- Added plugin settings for JAR file path, config file name, and auxiliary config file directories. I left the default for `config_file_name` to be `cflintrc.xml` as it was previously, but the standard naming for that file is `.cflintrc.xml` for the XML format and `.cflintrc` or `.cflintrc.json` for the JSON format. Should I just change the default?

**Comment by ckaznocha** [comment]
@KamasamaK Wow, that's great, thanks! I don't use this plugin much anymore so I wasn't aware of the changes. I'll look in to the version checking when I have a bit of time.

**Comment by KamasamaK** [comment]
Submitted PR #14

**Comment by KamasamaK** [comment]
Sorry. I noticed that the Travis build failed. Submitted PR #16 

I'm not familiar with how Sublime's Package Control works. Does the repo need to be resubmitted on each update?

**Comment by ckaznocha** [comment]
I need to bump the version and make a github release. Package control will just pick it up once thats done. This change will be a new major version. Was going to fix the lint issue when I bumped the version but I see you've done it already, thanks!
