### ISSUE TITLE
CFLint wiki content

### ISSUE THREAD

**Issue by TheRealAgentK** [ckaznocha/SublimeLinter-contrib-CFLint#18]
We're cleaning up the CFLint Wiki and I was wondering if this page:

https://github.com/cflint/CFLint/wiki/Installing-CFLint-&-Sublime-Linter-Plugin

would be better suited on your end? Not sure if it's necessary anymore after @KamasamaK did some PRs to your project.

Let me know! :)

**Comment by KamasamaK** [comment]
The part of the **Installation and setup** that is still useful is in the `README.md`. I can probably add a bit more stuff here, but mostly the links.

**Comment by TheRealAgentK** [comment]
Ok, so that means that if I remove that wiki page on the CFLint wiki and properly refer people to this project from our Readme (that I'm currently rewriting from scratch for 1.2.0), the Wiki page won't be missed? :)

**Comment by KamasamaK** [comment]
I think that once @ckaznocha creates a new release, removing that wiki page should be fine. I'm also waiting to hear if the XML config for CFLint is going to actually be deprecated, because then I would like to make a few changes since this plugin still defaults to that format.

**Comment by TheRealAgentK** [comment]
Ok, that makes sense. Just mentioning @ryaneberly here to make him aware of the relationship between https://github.com/cflint/CFLint/issues/352 and this issue here.

**Comment by TheRealAgentK** [comment]
oki, thx @ckaznocha. Once we've got 1.2 out the wiki will pretty much be gone and all the info will be in the READ/user manual, I'll make sure to put some links in place from your README via PR.
