### ISSUE TITLE
Windows Sublime3 cflint extraction issue

### ISSUE THREAD

**Issue by andrew-mikos** [ckaznocha/SublimeLinter-contrib-CFLint#6]
Receiving the error 
```
SublimeLinter: WARNING: no cflint version could be extracted from:


C:\Program Files\Sublime Text 3>java -jar C:\Users\andrew.mikos\workspace\zAssorted\CFLint-0.4-all.jar -version 

CFLint 0.4

```

in the console when trying to initialize the linter on a cfm or cfc file. The batch file set up is a single line and as follows: 

```
java -jar C:\Users\andrew.mikos\workspace\zAssorted\CFLint-0.4-all.jar %*
```

It works fine running through command line, however it can't seem to extract the version when run via SublimeLinter. The output in the console shows carriage return characters following all 3 lines, which may be related.

**Comment by ryaneberly** [comment]
see https://github.com/cflint/CFLint/issues/33
