### ISSUE TITLE
User interface frozen on save

### ISSUE THREAD

**Issue by laserbyte** [ckaznocha/SublimeLinter-contrib-CFLint#7]
Mac OS 10.8.5
Sublime build 3083

SublimeLinter-contrib-CFLint plugin
https://github.com/ckaznocha/SublimeLinter-contrib-CFLint

CFLint 0.2.0
https://github.com/cflint/CFLint

With the lint mode set to background every time I save a file I get the spinning beach ball for a few seconds and the user interface is frozen. Presumably the plugin is running cflint and waiting for that to return which ties up the user interface. I base this assumption on when I run CFLint from the command line it takes about the same amount of time to process the file as the interface is frozen when I save.

**Comment by KamasamaK** [comment]
This was probably solved by [SublimeLinter 3 PR #271](https://github.com/SublimeLinter/SublimeLinter3/pull/271)
