### ISSUE TITLE
Plugin installation via Package Control, plugin SublimeLinter-contrib-CFLint not found

### ISSUE THREAD

**Issue by GSmurf** [ckaznocha/SublimeLinter-contrib-CFLint#8]
Hi,

I install many other plugin in my sublime text 3 but when I type "CFLint" the package list not show "SublimeLinter-contrib-CFLint".

There are a problem about ?

**Comment by ckaznocha** [comment]
Its showing up for me just fine when following the steps here: https://github.com/ckaznocha/SublimeLinter-contrib-CFLint#plugin-installation

![screen shot 2015-09-04 at 4 39 30 pm](https://cloud.githubusercontent.com/assets/1851985/9694093/9abacd16-5323-11e5-92ec-054c84f4d200.png)

**Comment by GSmurf** [comment]
I have seen this steps and followed them, but no new instructions other than usualy, this install on my work's computer doesn't work, at home I have no problem !!?!

Some Proxy parameters exists ? or you have a trick's to follow to know why I meet this problem ?

![sublimelinter-contrib-cflint-01](https://cloud.githubusercontent.com/assets/2247079/9927641/a228ed6a-5d20-11e5-8dec-bfe9c41814db.PNG)
![sublimelinter-contrib-cflint-02](https://cloud.githubusercontent.com/assets/2247079/9927642/a2291ec0-5d20-11e5-83b7-90a3cee144fe.PNG)

**Comment by ckaznocha** [comment]
Hi @GSmurf I'm sorry you're still having issues. I can assure you I'm not using any tricks or proxies. I've confirmed it works from multiple internet connections.

The only reason I can think of that this would be happening to you is that it's already installed. Can you please confirm on the machine you're having issue on that the plugin isn't already installed by opening the command palette and navigating to `Package Control: List Packages` and make sure that it is **not** listed there?
